### PR TITLE
R4 C-CDA Companion Guide Examples from New Templates

### PR DESCRIPTION
**Pull request by jddamore**
This also includes commits from the prior pull request of https://github.com/HL7/C-CDA-Examples/pull/120

If you pull this one in, you'll get both and you can close the other pull request

### CODE REVIEW

**Comment by dhit-mdavis** [comment]
Hi John. My name is Mat Davis from Dynamic Health IT.

Can you reconfirm the Disability Status Observation example? 

I believe the structure doesn't follow the template.

**Comment by jddamore** [comment]
@dhit-mdavis I just emailed Brett and Gay regarding. I cc-ed Raychelle so she can send to you. I think you might be right, but I didn't author, so sending back to them for comment. If we change, we might need to open JIRA as technical errata since it's that way in the PDF https://www.hl7.org/ccdasearch/pdfs/2.16.840.1.113883.10.20.22.4.505.pdf

**Comment by dhit-mdavis** [comment]
@jddamore thanks John! I've coordinated with Raychelle and we'll report the issue to Jira on our end.

I've requested an account from here to get me started - https://jira.hl7.org/secure/Dashboard.jspa

**Comment by brettmarquard** [comment]
Got a chance to peek -- please open a JIRA and put the number here!

**Comment by dhit-mdavis** [comment]
Okay Brett, Jira ticket entered - let me know if it anything else is needed from me and I got ya' covered.

https://jira.hl7.org/browse/CDA-20769

**Comment by brettmarquard** [comment]
Approved on SD 9/21!

**Comment by dhit-mdavis** [comment]
Thanks for the update John!

**Pull request merged**
